### ISSUE TITLE
The 'x-checker-data' field of the 'obs-backgroundremoval' module doesn't catch new releases

### ISSUE THREAD

**Issue by GeorgesStavracas** [flathub/com.obsproject.Studio.Plugin.BackgroundRemoval#5] opened 2023-07-13 19:35 UTC
While doing bug triage in OBS Studio (https://github.com/obsproject/obs-studio/issues/9247) we noticed that the background removal plugin was outdated. The latest release is `1.1.1`, Flathub has `1.0.1`.

Upon further inspection, I noticed that the two most recent tags are `1.1.0` and `1.1.1`. Before that, the tags were `v1.0.3`, `v1.0.2`, etc. Notice that the `v` character was dropped from recent tags.

The problem is that the [data checker data in this repository](https://github.com/flathub/com.obsproject.Studio.Plugin.BackgroundRemoval/blob/master/com.obsproject.Studio.Plugin.BackgroundRemoval.yaml#L59-L61) looks for tags that look like `vX.Y.Z`, so the new releases weren't picked up by the bot.

I'm not sure if the removal of the `v` character from upstream tags was intentional, or if the regex in this repository is outdated, so I won't propose any change without further suggestion. I'll leave to the maintainer's discretion!

**Comment by drieks** [comment] 2023-07-24 08:00
I created a bug report here: https://github.com/royshil/obs-backgroundremoval/issues/404

**Comment by umireon** [comment] 2023-09-21 14:33
Will be fixed by #6

**Comment by umireon** [comment] 2023-09-22 13:03
@royshil Can you close this issue? Fixed by #6

**Comment by royshil** [comment] 2023-09-22 13:08
fixed.

**Comment by hardpenguin** [comment] 2023-12-07 13:27
I am still stuck on 1.0.1.

While I understand the issue was fixed upstream, I am still unable to update. I tried removing the currently installed version 1.0.1 and installing said runtime again but it installs yet again in the outdated version 1.0.1. And `flatpak remote-info --log` also shows that 1.0.1 is the latest one available for installation.

I want to get the most recent version which is 1.1.6 (and soon 1.1.7). And as I understand, it should be available for installation already: https://github.com/flathub/com.obsproject.Studio.Plugin.BackgroundRemoval/blob/master/com.obsproject.Studio.Plugin.BackgroundRemoval.yaml

Can you double check the issue was in fact fixed? Or advise how to proceed to update?

Should I open a new issue or can we reopen this one?

**Comment by hardpenguin** [comment] 2023-12-07 16:15
Okay the helpful users over at discourse.flathub.org explained to me that it seems the latest build is not available:

https://discourse.flathub.org/t/help-stuck-on-an-outdated-version-of-runtime/5602/7

Please fix? I want to use a more recent version than 1.0.1 :)

**Comment by royshil** [comment] 2023-12-08 16:12
i'm tryin to fix at #8

**Comment by royshil** [comment] 2023-12-10 04:27
@hardpenguin the build is successful
do you want to try `flatpak install --user https://dl.flathub.org/build-repo/69583/com.obsproject.Studio.Plugin.BackgroundRemoval.flatpakref`?

**Comment by hardpenguin** [comment] 2023-12-10 11:36
It seems to be working OK! The only issue is that the version number is not visible when using `flatpak info` or `flatpak list`.

From the log file:

```
12:30:14.837: Failed to load 'pl-PL' text for module: 'obs-backgroundremoval.so'
12:30:14.837: [obs-backgroundremoval] Plugin loaded successfully (version 1.1.7)
12:30:14.837: [obs-backgroundremoval] Config folder does not exist, creating: /home/van/.var/app/com.obsproject.Studio/config/obs-studio/plugin_config/obs-backgroundremoval/
12:30:14.837: [obs-backgroundremoval] Failed to open config file /home/van/.var/app/com.obsproject.Studio/config/obs-studio/plugin_config/obs-backgroundremoval/config.ini
12:30:15.162: [obs-backgroundremoval] Latest release is
```

**Comment by royshil** [comment] 2023-12-10 21:43
@hardpenguin 
What is the expected output would you say?
I'm not a big user of flatpak
So right now flatpak doesn't provide a version at all or the wrong one?

**Comment by hardpenguin** [comment] 2023-12-11 10:29
The log file I presented above was from OBS itself, it confirmed the plugin was correctly loaded in the newest version (1.1.7).

As of flatpak:

```
$ flatpak remote-info flathub com.obsproject.Studio.Plugin.BackgroundRemoval

Background Removal - Remove the background from your camera video

        ID: com.obsproject.Studio.Plugin.BackgroundRemoval
       Ref: runtime/com.obsproject.Studio.Plugin.BackgroundRemoval/x86_64/stable
      Arch: x86_64
    Branch: stable
   License: GPL-2.0
Collection: org.flathub.Stable
  Download: 152.2?MB
 Installed: 408.2?MB

    Commit: 060f51e731a87371c9e491da991bbd7a525834bbc0fe8239674f03ddb7df59c3
    Parent: c8a808c942f834189bec4c7dbce7d7113eed940429e30efcb4cc9baf6e5ec42d
   Subject: Upgrade to org.kde.Sdk//6.5 (9a8164d4)
      Date: 2023-12-08 16:02:40 +0000
```

```
$ flatpak list
Name                                      Application ID                                      Version      Branch          Origin                      Installation
Discord                                   com.discordapp.Discord                              0.0.37       stable          flathub                     user
Protontricks                              com.github.Matoking.protontricks                    1.10.5       stable          flathub                     user
Flatseal                                  com.github.tchx84.Flatseal                          2.1.0        stable          flathub                     user
OBS Studio                                com.obsproject.Studio                               30.0.0       stable          flathub                     user
Background Removal                        com.obsproject.Studio.Plugin.BackgroundRemoval                   stable          backgroundremoval-origin    user
SGDBoop                                   com.steamgriddb.SGDBoop                             1.2.8        stable          flathub                     user
(..)
```

See the empty space above on the list? The `version` field is missing altogether. For comparison, this is what `flatpak remote-info` outputs for Discord, the `version` field is showing the current version:

```
$ flatpak remote-info flathub com.discordapp.Discord

Discord - Messaging, voice and video client

        ID: com.discordapp.Discord
       Ref: app/com.discordapp.Discord/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 0.0.37
   License: LicenseRef-proprietary
Collection: org.flathub.Stable
  Download: 96.8?MB
 Installed: 238.0?MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: c02762088b38869cd03823a877d1f0a2da6a061933d39a51da6fe21eb9f1c47a
    Parent: bdac3a2952c5d06590841b94d6697e47dd7983af5d323c0b1fa42f960c0013bc
   Subject: Update discord-0.0.36.tar.gz to 0.0.37 (71dddaad)
      Date: 2023-12-05 21:29:10 +0000
```

The way I understand, _flathub_ now has the version from December 8th. _I_ have the version installed through the command you suggested yesterday.

**Comment by hardpenguin** [comment] 2023-12-11 10:31
FYI I am not an expert on flatpak either and I encourage you to seek second opinion from the flathub community using channel you prefer: https://flatpak.org/about/

**Comment by royshil** [comment] 2023-12-12 22:54
@hardpenguin i added the release version to the metadata
can you check plz?

**Comment by hardpenguin** [comment] 2023-12-13 11:26
I installed the test build [87516](https://buildbot.flathub.org/#/builders/6/builds/87516) per instructions in https://github.com/flathub/com.obsproject.Studio.Plugin.BackgroundRemoval/pull/8 .

```
$ flatpak info com.obsproject.Studio.Plugin.BackgroundRemoval

Background Removal - Remove the background from your camera video

          ID: com.obsproject.Studio.Plugin.BackgroundRemoval
         Ref: runtime/com.obsproject.Studio.Plugin.BackgroundRemoval/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.1.7
     License: GPL-2.0
      Origin: backgroundremoval-origin
  Collection: org.flathub.Test.Build70183
Installation: user
   Installed: 436.7?MB

      Commit: 11668018c454c5264f6b512190c5e8ba0f0cc24447d6dfb42cd83a5620655fc8
     Subject: Update com.obsproject.Studio.Plugin.BackgroundRemoval.metainfo.xml (ccfd34e0)
        Date: 2023-12-12 22:50:49 +0000
```

```
$ flatpak list
Name                         Application ID                          Version  Branch      Origin                   Installation
Discord                      com.discordapp.Discord                  0.0.37   stable      flathub                  user
Protontricks                 com.github.Matoking.protontricks        1.10.5   stable      flathub                  user
Flatseal                     com.github.tchx84.Flatseal              2.1.0    stable      flathub                  user
OBS Studio                   com.obsproject.Studio                   30.0.0   stable      flathub                  user
Background Removal           ?roject.Studio.Plugin.BackgroundRemoval 1.1.7    stable      backgroundremoval-origin user
SGDBoop                      com.steamgriddb.SGDBoop                 1.2.8    stable      flathub                  user
(..)
```

The version number is being displayed correctly now. Nothing left but to publish it now.

There is another issue with this build related to the verison number though, it displays this dialog by default: 

![Screenshot_20231213_122137](https://github.com/flathub/com.obsproject.Studio.Plugin.BackgroundRemoval/assets/20478460/b8dc3416-6d51-4cba-835c-d3696338c54c)

Yes, I can disable the update checks for the plugin as a workaround.

However the issue is that:

1. I am already on the latest version 1.1.7
2. Should this dialog even be displayed when using the flatpak version of the plugin? Since it is gonna be automatically updated during the system updates routine along with the rest of flatpak updates. Unlike Windows .exe, macOS .pkg, and Linux .deb this does not require manual download and installation.

**Comment by hardpenguin** [comment] 2023-12-13 11:26
Btw @royshil I want to thank you very much for addressing this issue and updating the flatpak build <3

**Comment by royshil** [comment] 2023-12-13 14:29
i'm going to merge this in for now, and the update checked problem needs to be resolved on the main repo side, here in flatpak i can't make changes to the code (without significant overhead)

**Comment by royshil** [comment] 2023-12-13 17:23
closing. updated the recipe and added the versioning

**Closed as completed by royshil** 2023-12-13 17:23 UTC
